version: "3"
services:
  go-graphql:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./src:/go_graphql_app
    ports:
      - 8080:8080
    tty: true
    container_name: go-graphql